id: 192ec5a7e78040168a0833e0df6b07da
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_247-Distinguishing_Phenomena_and_What_Is_Meaningful-v1
  language: en
  author: ''
  volume: {}
